### ISSUE TITLE
Enhancement: multi-threaded downloading for large files (ESP32)

### ISSUE THREAD

**Issue by MATTYGILO** [SpotlightKid/mrequests#9]
Hi I think a very useful tools for downloading large files using multithreading on mrequests on an esp32:

The proposed enhancement, "multi-threaded downloading for large files (ESP32)," holds significant potential for improving the functionality and user experience of Micropython on the ESP32 platform. This feature would be particularly beneficial for scenarios where large files need to be downloaded efficiently and quickly.

By implementing multi-threaded downloading, users working with Micropython on ESP32 would gain the advantage of faster download times for substantial files. The ability to download different parts of a file in parallel would make better use of available network bandwidth and reduce overall download times. This enhancement aligns well with the increasing demand for efficient data handling in embedded systems, and it could lead to enhanced performance and responsiveness in applications built with Micropython.

**Comment by SpotlightKid** [comment]
After working some more on `mrequests` and thinking about this feature request I have come to the conclusion that I this is not something I think fits the scope of this module and that I don't plan on adding this.

The `mrequests` module is becoming already more complex than I initially planned it to be and it is becoming more difficult to maintain compatibility with more memory restricted ports like the `esp8266`. Also, without evidence in the form of benchmarks, I doubt that single-threaded operation is a significant performance bottleneck for the HTTP requests in typical embedded applications. It might more sense on the `unix` port, but then multi-threaded download support should be implemented in a separate module, IMHO. `mrequests` tries to maintain compatibility and feature parity across MicroPython ports (exceptions have to be made with TLS support, since some ports have crippled `ssl` modules).

If you have and implementation, which implements the requested feature and fits the scope of the `mrequests` module, feel free to submit a PR and I'll review it with an open mind.
